### PR TITLE
Feature/add schedule

### PR DESCRIPTION
**Pull request by Hout**
Added schedule extraction & report planned temperature when it differs from the setpoint AND mode is follow schedule.

### CODE REVIEW

**Comment by RichieB2B** [comment]
Thanks! Looks like this PR does not depend on https://github.com/watchforstock/evohome-client/pull/117, right? It sets a label type="planned" when Evohome is preheating, and also when Evohome lowers the setpoint before the planned end of a heating period (precooling). 

prometheus_client keeps reporting the values for unique labels until they are removed. Should type="planned" be removed when planned == setpoint? Or should the planned temperature be output all the time, simply following the schedule and not only when planned != setpoint? Detecting/visualizing preheating+precooling can then be done in prometheus using a compare between planned and setpoint.

**Comment by Hout** [comment]
> Looks like this PR does not depend on [watchforstock/evohome-client#117](https://github.com/watchforstock/evohome-client/pull/117), right? 

Correct!

> prometheus_client keeps reporting the values for unique labels until they are removed. Should type="planned" be removed when planned == setpoint? 

That was my intention :-)

> Or should the planned temperature be output all the time, simply following the schedule and not only when planned != setpoint? Detecting/visualizing preheating+precooling can then be done in prometheus using a compare between planned and setpoint.

~~I am less experienced in Prometheus but I want to prevent to be the carpenter who wants to fix everything with a hammer and a nail (e.g. Python). So I see the advantage of the latter option, however I also think that the amount of data might be a bit raw and the post processing in Prometheus might put off people.~~ Closer look: yes this is a better idea.

**Comment by Hout** [comment]
I noticed that the permanent state is not reflected in the exporter results; investigating...

**Comment by RichieB2B** [comment]
Thanks! I also added a line to remove the planned temperature when the Honeywell servers are unavailable.

**Pull request merged**
