### PR TITLE
WIP: add scheduled temperature to the metrics

### PR DESCRIPTION
**Pull request by Hout**
Depends on an update on the evohome-client. Pull request sent.

Do not pull yet (if at all ;-); still work in progress as I want to align it with your code

### CODE REVIEW

**Comment by RichieB2B** [comment]
Thanks! I already added some of your improvements like the Black formatting.

**Comment by RichieB2B** [comment]
I have added a "setpointmode" label in https://github.com/RichieB2B/evohome-exporter/commit/bbbe345536548691b48ba79832eea5af86681f76 which requires a [patch](https://github.com/watchforstock/evohome-client/pull/118) to evohomeclient2.
Does this suite your needs?

**Comment by RichieB2B** [comment]
Ok, using labels to store state is a bad idea. I'm now using Enum instead. So the zone and system state is available as
```
evohome_zone_mode{evohome_zone_mode="x",id="y",name="z",thermostat="EMEA_ZONE"} 
evohome_temperaturecontrolsystem_mode{evohome_temperaturecontrolsystem_mode="x"}
```

**Comment by Hout** [comment]
> I have added a "setpointmode" label in [bbbe345](https://github.com/RichieB2B/evohome-exporter/commit/bbbe345536548691b48ba79832eea5af86681f76) which requires a [patch](https://github.com/watchforstock/evohome-client/pull/118) to evohomeclient2.
> Does this suite your needs?

Not quite but it helps; However I really want to see the scheduled temperature when the schedule is active so I can show whether or not the evohome is doing its adaptive warming properly.

**Comment by Hout** [comment]
I will have a look at the conflicts early next week

**Comment by RichieB2B** [comment]
> Not quite but it helps; However I really want to see the scheduled temperature when the schedule is active so I can show whether or not the evohome is doing its adaptive warming properly.

The scheduled temperature is the setpoint while the evohome_zone_mode is FollowSchedule. One thing missing is logging when (and for how long) Evohome is using adaptive mode. This could be a special evohome_zone_mode for example FollowScheduleAdaptive when Evohome reports FollowSchedule but the current time is not in the schedule window.

**Comment by Hout** [comment]
The following only applies when there is a schedule and in adaptive mode, which I think most people use.

I tend to think from the user's perspective. In this case that is the schedule that I programmed the Evohome with. In addition, I want to see whether Evohome and the radiators get the rooms up to the right temperature in time. I am less interested in the setpoint as it displays the temperature that the thermostat uses in order to heat up the room, but without a reference to the schedule that I use. E.g. if I want the room to heat up from 16 degrees to 21 degrees at 8:00, then I expect a rising temperature ending exactly flat at 20 degrees at 8:00, and not a setpoint of 20 degrees at 6:00. I need that reference of the schedule.

E.g. like this:
image
It shows that the heating started too early for this room.

**Comment by RichieB2B** [comment]
Ok, so you want an additional temperature metric that shows the planned temperature for each zone. This could be type="planned" of the existing evohome_temperature_celcius Gauge. I like your idea of only reading the schedule once per hour. 

Let me know if you have a patch that applies to the current code.

**Comment by Hout** [comment]
Yup will do.

That depends on the PR that I sent for evohomeclient module though...

**Pull request closed without merging**
